### ISSUE TITLE
Player hand should not be able to overflow off screen

### ISSUE THREAD

**Issue by JonMasson** [kilikfan/treasure#16]
If the player's hand has too many resources, they will overflow off the screen.

Need to find a way to avoid this, and make it work on smaller screens

**Comment by ghost** [comment]
We could potentially use a [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html) and a `MediaQuery` to limit the overall width of the stack to 80% of the screen or whatever. And then the resources would gradually stack on top of each other as they became more constrained for space.

**Comment by kilikfan** [comment]
After recent changes and testing of the player hand UI this issue is no longer required.
