### ISSUE TITLE
Extend cost payment to allow different options

### ISSUE THREAD

**Issue by kilikfan** [kilikfan/treasure#19]
Allow multiple different ways of paying for a cost, e.g. [Resource.LANDLUBBER, Resource.DOUBLOON] or [Resource.CREW, Resource.DOUBLOON]

**Comment by kilikfan** [comment]
Potentially add in context specific costs, e.g. half of current crew as well.

**Comment by ghost** [comment]
For context-specific costs, I would suggest that the existing `getActions` method could take the current gameState - then it becomes pretty easy to do calculations based on the player's hand etc.

**Comment by samuel-bradley** [comment]
I've just moved https://github.com/kilikfan/treasure/issues/73 into in progress, assigned to myself - Mark suggests this one can be closed since only the component which is duplicated by 73 is left: https://professionalworkers.slack.com/archives/CTXKQ3UQ5/p1614725592019000

**Comment by kilikfan** [comment]
As above, closing this one and the remainder can be done under #73
