### ISSUE TITLE
Block some actions based on context

### ISSUE THREAD

**Issue by kilikfan** [kilikfan/treasure#20]
Only enable some actions if they are the only available ones, e.g. only allow a discard if the other options cannot be afforded.

**Comment by ghost** [comment]
Is this a thing? Would be in favour of always allowing the flexibility - might be the edge case where you can afford an option but don't want to do it?

Or am I just forgetting how underhand worked?

**Comment by ghost** [comment]
Ok, I went back to the doc and looks like sometimes this is a thing (e.g. not getting away scot-free for scurvy unless you genuinely can't afford to lose food or crew).

I mentioned in another issue, but if `getActions()` took the game state we'd have flexibility for some smarter logic around the actions. So perhaps add the concept of actions being disabled and compute this in a bespoke way where it's needed as an MVP approach?
