### ISSUE TITLE
Find a way to avoid having to import each card individually

### ISSUE THREAD

**Issue by JonMasson** [kilikfan/treasure#22]
Currently each card has to be imported individually:
```
import 'package:treasure_of_the_high_seas/model/card/basic/a_rival_ship.dart';
...
...
...
import 'package:treasure_of_the_high_seas/model/card/basic/plunder_a_wreck.dart';
```
This may get unmanageable when dealing with lots of cards, can we find a way to avoid this?

Maybe an `index.dart` file in the `model/card/` folder which re-exports all the cards? (or in each card category folder)

Not sure if this is actually possible in dart though!

**Comment by kilikfan** [comment]
Don't know whether you can import all of the cards folder and refer to things that way? But you're right we need to do something for it definitely

**Comment by ghost** [comment]
FFS wow, looks like wildcard imports is another thing to add to the "basic features Dart doesn't have" list.

Some workarounds suggested in this SO post: https://stackoverflow.com/questions/25860342/how-can-i-import-all-files-in-a-folder. So perhaps we have a `deck.dart` which exports all the cards, and then more heavyweight files requiring lots of cards can import that. But yucky boilerplate :/
