### ISSUE TITLE
Display action costs/rewards

### ISSUE THREAD

**Issue by JonMasson** [kilikfan/treasure#24]
Display the costs and rewards for each action

![Deal first card](https://user-images.githubusercontent.com/5371565/79050723-dc4db080-7c23-11ea-8da5-2ab5d951da49.png)

**Comment by ghost** [comment]
Plan: Implement something like:

```
class CardActionDetails {
    String description;
    List<Resource> cost;
    List<Resource> reward;
    Int cardsToScry;
    
    const CardActionDetails(this.description, this.cost, {this.reward, this.others, this.cardsToScry, ...});
}
```

All actions with return one of these, which the UI can use to render the cards appropriately.
