### ISSUE TITLE
Refactor cards to have 3 actions rather than a List<>

### ISSUE THREAD

**Issue by JonMasson** [kilikfan/treasure#25]
- Cards should have `actionOne`, `actionTwo` and `actionThree` instead of a List<>
- actionThree should be optional
- `lib\screens\play\current_card\card_actions\card_actions.dart` (and its tests) should be updated to reflect this change

**Comment by JonMasson** [comment]
Not sure if this is actually something we want, would we ever want a card with four or more actions?

**Comment by kilikfan** [comment]
I don't think we want this, currently the code will work with 2 or 3 actions, and a list is neat.
