### ISSUE TITLE
Be able to perform actions

### ISSUE THREAD

**Issue by JonMasson** [kilikfan/treasure#29]
- Should be able to click on card actions in the ui, and have the action perform
 - Perhaps for now costs should be auto-deducted, preferring normal resources over maps
 - Actions that can't be afforded should not be clickable, ideally would be greyed out or something

**Comment by ghost** [comment]
The auto-deduction is already done. I think if you just add an `onPress` which calls `performAction`, all the cost deduction, moving onto the next card etc should just work :crossed_fingers:
