### ISSUE TITLE
Redux equivalent for Flutter?

### ISSUE THREAD

**Issue by ghost** [kilikfan/treasure#38]
In my latest PR I had to drill game state down through quite a few UI components in order to provide it to `CardActionPanel`. It might be worth us looking into suggested strategies for managing state in flutter - perhaps something like Redux where the state is centralised someplace where individual components can reach in and grab the parts they care about.

**Comment by kilikfan** [comment]
[Brief overview in Flutter](https://flutter.dev/docs/development/data-and-backend/state-mgmt)
[Choice of options in Flutter (including a Redux package)](https://flutter.dev/docs/development/data-and-backend/state-mgmt/options)
Watched the linked video from Google I/O and provider and smaller states seems to be a pretty sensible approach, might give that a try on something.
