### ISSUE TITLE
Static code analysis / linting

### ISSUE THREAD

**Issue by ghost** [kilikfan/treasure#59]
Worth us having a look to see if there are any good tools for static code analysis of Dart. Ideally, we'd add a step to github actions so it's consistent for everyone - failing this, I guess we could look through options in Android Studio and agree a common set to enable (and probably document them in the README).

This would be for things that aren't compile errors, but more code style things like not using `var` when `final` would do. 

At the very least there's `flutter analyze` which we should totally add to our actions pipeline, but there might be more we can do as well.

**Comment by ghost** [comment]
Related: We could use git hooks to automatically run `dartfmt` to keep our formatting consistent, which might be nice. [pre-commit](https://pre-commit.com/) is something we've got on with fairly well at my work, although would need to check it's compatible for windows machines!

**Comment by kilikfan** [comment]
Just had a quick search and https://medium.com/flutter-community/code-analysis-linting-in-flutter-and-dart-flutter-explained-3014a481e5e looks like a good starting place.
