### ISSUE TITLE
Active quests view

### ISSUE THREAD

**Issue by kilikfan** [kilikfan/treasure#86]
Have a button next to quick rules to view active quests. Either just the card name and which stage of which quest it is, or maybe allow to view the entire card to see what costs you need to save up for.

**Comment by samuel-bradley** [comment]
Notes from chat:

"Would be a new button in the top bar and maybe a swipeable thing like the discard pile? Or into a new page that's a list of card names, but only displaying ones in the deck or discard that have quest type

So we want to know the active stages. So as I said above just whichever quest cards are in the deck or discard piles

Yeah not sure whether we'd want an intermediate page or just straight into the card viewer swiper"
